version: '3.8'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: poit
      MYSQL_USER: stuuser
      MYSQL_PASSWORD: stupassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  mariadb_data:
